# Generated by Django 2.2.12 on 2022-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('department', models.TextField(default='')),
                ('isAdmin', models.IntegerField(default=0)),
            ],
        ),
    ]
