# Generated by Django 3.2.5 on 2022-03-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir_number', models.IntegerField(default=0)),
                ('ir_date', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('vendorName', models.CharField(max_length=200)),
                ('po_number', models.CharField(max_length=200)),
                ('po_date', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('invoice_amount', models.IntegerField(default=0)),
                ('invoice_number', models.IntegerField(default=0)),
            ],
        ),
    ]
